### ISSUE TITLE
data_gen code execution error

### ISSUE THREAD

**Issue by 3202336152** [changhaonan/A3VLM#1]
Thank you for your excellent work. Is the parameter --data_name="all" in data_gen wrong? The dataset folder does not have this name, but all the ID labels are used as folder names.
Running the render_robot_pyrender.py file will report an error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sda/lyf/dataset/partnet_mobility/all/meta.json'

**Comment by changhaonan** [comment]
Hi,
Thanks for your interest. I fixed the problem. Let me know if it still exit on your side.

**Comment by 3202336152** [comment]
The code still reports an error. You can try running this code once. I still don’t know what the parameter all means. There seems to be a problem with the render_data_item_with_idx function.
Rendering 2347 datasets
0%| | 0/2347 [00:00<?, ?it/s]Error in 3990: Cannot connect to "None"
Error in 2113: Cannot connect to "None"
Error in 103333: Cannot connect to "None"
Error in 101868: Cannot connect to "None"
Error in 10562: Cannot connect to "None"
Error in 100466: Cannot connect to "None"
Error in 9065: Cannot connect to "None"
Error in 48413: Cannot connect to "None"
Error in 8903: Cannot connect to "None"
Error in 101293: Cannot connect to "None"
Error in 102619: Cannot connect to "None"
Error in 12594: Cannot connect to "None"
Error in 101004: Cannot connect to "None"

**Comment by changhaonan** [comment]
This error is because some servers need to specify render device. I have add a environment variable in code. If there still exists error related with "EGL", you can try to run `sudo apt-get install libglfw3-dev libgles2-mesa-dev`.

**Comment by 3202336152** [comment]
thank you for your reply. Some builds work fine, but this error occasionally appears.
Error in 0%| | 1/2347 [05:10<202:37:55, 310.94s/it]Error in 3593: string is not a file: /home/sda/lyf/dataset/partnet_mobility/3593/textured_objs/new-1.obj
Error in 7138: string is not a file: /home/sda/lyf/dataset/partnet_mobility/7138/textured_objs/new-8.obj

**Comment by changhaonan** [comment]
I explained the issue in the README. This is the problem of raw PartNet-mobility dataset, as there are some files missing in the data they provided.
